### ISSUE TITLE
The console didn't print String on my OSX10.10.5

### ISSUE THREAD

**Issue by kenchowcn** [erlide/erlide#236]
Hi,vladdu, I encountered a problem when I was running hello.erl on ERLIDE, the console didn't print "hello erlide!~n", I can't figure it out, and what is the purpose for the erlide_debug.txt? 

I've tried my code in ERL command is ok.

**Erlang/OTP 17**

**OSX10.10.5**

this is the details:

![6062cd1e-f830-4a81-b5cd-a20ff71b9ac4](https://cloud.githubusercontent.com/assets/1762018/9793601/c2424798-5818-11e5-8a6d-bdca24e4cc81.png)

thank you for your help.

**Comment by vladdu** [comment]
Hi Ken,

First, erlide_debug.txt should not be created unless internal erlide debugging is enabled, I will check if there is something wrong with that flag. You can ignore the file.

Regarding the console, it should work, see below.
![console](https://cloud.githubusercontent.com/assets/9707/9800004/d28d71d0-580a-11e5-9608-78fb8d62a0b9.png)

Do you get anything in the console when calling hello:hello()?

**Comment by kenchowcn** [comment]
1. As you can see the picture of my first post , when I clicked run button, the  the eclipse console didn't get anything, except eshell prompt and erl is running indeed, but my erlang program didn't execute.

2. And another thing that I found, every time when I click run, the eclipse will generate a new console, look at the picture of below. It unlike your console that I can see erlang program will compile in the same console. 

![83574f11-e7c8-4060-94f5-863a21c88401](https://cloud.githubusercontent.com/assets/1762018/9815692/99d53966-58ca-11e5-97ad-c14d79113af7.png)

thank you for your replying, if I described not clear please ask.

**Comment by vladdu** [comment]
Ah, I see. 

1. When you choose "run", only the Erlang runtime is started. It can't know which function to call. If you add hello:hello/0 in the run configuration dialog, under "start", then the function will get called, but the output will not be visible because it goes to the default console, not the one that is opened by Eclipse. If in the console you enter "hello:hello()." you will see the output. 

I will add a note about using io:format in the initialization functions.

2. Because "run" starts the runtime, you don't need to press it every time: just once is enough and when saving a file it is compiled and the code reloaded. Then in the console you call your functions again.

I suppose that this needs some extra documentation too.

**Comment by kenchowcn** [comment]
oh, I think I understand now, I just learn some erlang, I through erlide will like Java console, I just tried typing hello:hello(). in the eshell(console), then I got the string that I expected. 

Thank you for every much.
